"""SmartServe V10 — expanded service catalog.

This module is the single source of truth for the marketplace catalogue that
SmartServe V10 seeds *additively* into the existing ``services`` table.

Design rules
------------
* Every entry carries the V10 category metadata: subcategory, required skill,
  certification requirement, risk level, allowed provider types, equipment,
  expected duration, pricing model and possible parts.
* The existing V9.3 rows (Plumbing, Electrical, ...) are preserved. We only
  ``UPDATE`` their metadata and ``INSERT`` the new rows. Nothing is deleted.
* Risk levels drive provider eligibility. ``HIGH`` / ``RESTRICTED`` services can
  only be accepted by providers whose verified skill passport allows them.
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# Risk levels
# ---------------------------------------------------------------------------
RISK_LOW = "LOW"            # Any approved provider
RISK_MEDIUM = "MEDIUM"      # Provider must offer the service and have the skill
RISK_HIGH = "HIGH"          # Skill verification or certification required
RISK_RESTRICTED = "RESTRICTED"  # Professional licence / certification required

RISK_LEVELS = (RISK_LOW, RISK_MEDIUM, RISK_HIGH, RISK_RESTRICTED)

PROVIDER_TYPE_STUDENT = "student"
PROVIDER_TYPE_PROFESSIONAL = "professional"
PROVIDER_TYPE_ANY = "any"

# ---------------------------------------------------------------------------
# Broad categories  (hierarchical browsing: HOME > category > subcategory)
# ---------------------------------------------------------------------------
CATEGORIES = [
    {
        "key": "home_repair",
        "name": "Home Repair & Maintenance",
        "icon": "🔧",
        "description": "Plumbing, electrical, carpentry, painting and everyday home repairs",
        "sort_order": 10,
        "risk_level": RISK_MEDIUM,
        "allowed_provider_types": "any",
    },
    {
        "key": "appliance_electronics",
        "name": "Appliance & Electronics",
        "icon": "🔌",
        "description": "AC, refrigerator, washing machine, TV and device repair plus smart home setup",
        "sort_order": 20,
        "risk_level": RISK_MEDIUM,
        "allowed_provider_types": "any",
    },
    {
        "key": "cleaning_pest",
        "name": "Cleaning & Pest Control",
        "icon": "🧹",
        "description": "Deep cleaning, sofa/carpet care and licensed pest control",
        "sort_order": 30,
        "risk_level": RISK_LOW,
        "allowed_provider_types": "any",
    },
    {
        "key": "beauty_personal_care",
        "name": "Beauty & Personal Care",
        "icon": "💇",
        "description": "Salon at home, makeup, mehendi, grooming and wellness services",
        "sort_order": 40,
        "risk_level": RISK_LOW,
        "allowed_provider_types": "any",
    },
    {
        "key": "home_improvement",
        "name": "Home Improvement",
        "icon": "🏗️",
        "description": "Painting, waterproofing, wall décor, panels and modular furniture",
        "sort_order": 50,
        "risk_level": RISK_HIGH,
        "allowed_provider_types": "any",
    },
    {
        "key": "moving_support",
        "name": "Moving & Support",
        "icon": "🚚",
        "description": "Packers and movers, shifting, loading and local delivery help",
        "sort_order": 60,
        "risk_level": RISK_MEDIUM,
        "allowed_provider_types": "any",
    },
    {
        "key": "vehicle_services",
        "name": "Vehicle Services",
        "icon": "🛞",
        "description": "Two-wheeler and car mechanics, battery, tyres, detailing and roadside help",
        "sort_order": 70,
        "risk_level": RISK_HIGH,
        "allowed_provider_types": "any",
    },
    {
        "key": "education_digital",
        "name": "Education & Digital",
        "icon": "🎓",
        "description": "Home tutors, coding classes, computer training and device setup",
        "sort_order": 80,
        "risk_level": RISK_LOW,
        "allowed_provider_types": "any",
    },
    {
        "key": "pet_care",
        "name": "Pet Services",
        "icon": "🐾",
        "description": "Grooming, walking, sitting and basic pet care assistance",
        "sort_order": 90,
        "risk_level": RISK_LOW,
        "allowed_provider_types": "any",
    },
]

CATEGORY_BY_NAME = {c["name"]: c for c in CATEGORIES}


def _svc(
    name,
    category,
    subcategory,
    description,
    icon,
    *,
    duration="60–90 min",
    pricing_model="VISIT_PLUS_WORK",
    base_price=299,
    min_price=199,
    max_price=1499,
    risk=RISK_MEDIUM,
    required_skills=None,
    required_certification=None,
    allowed_provider_types=PROVIDER_TYPE_ANY,
    required_equipment=None,
    possible_parts=None,
    popular=False,
    keywords=None,
    assets=None,
    sort_order=100,
):
    """Compact service definition helper (keeps the catalogue readable)."""
    return {
        "name": name,
        "category": category,
        "subcategory": subcategory,
        "description": description,
        "icon": icon,
        "estimated_duration": duration,
        "pricing_model": pricing_model,
        "base_price": base_price,
        "min_price": min_price,
        "max_price": max_price,
        "risk_level": risk,
        "required_skills": required_skills or [name],
        "required_certification": required_certification,
        "allowed_provider_types": allowed_provider_types,
        "required_equipment": required_equipment or [],
        "possible_parts": possible_parts or [],
        "popular": 1 if popular else 0,
        "keywords": keywords or [],
        "asset_types": assets or [],
        "sort_order": sort_order,
    }


# ---------------------------------------------------------------------------
# The catalogue
# ---------------------------------------------------------------------------
SERVICES = [
    # ================= HOME REPAIR & MAINTENANCE ==========================
    _svc("Plumbing", "Home Repair & Maintenance", "Plumbing",
         "Taps, pipes, leaks, drains and bathroom fittings",
         "🔧", sort_order=10, popular=True, risk=RISK_MEDIUM,
         base_price=299, max_price=1499,
         required_equipment=["Pipe wrench set", "Plunger", "Sealant gun"],
         possible_parts=["Tap cartridge", "PTFE tape", "PVC elbow", "Washbasin waste coupling", "Ball valve"],
         keywords=["leak", "tap", "pipe", "drain", "blockage", "water", "flush", "toilet", "commode", "sink"],
         assets=["Water system", "Bathroom fitting"]),
    _svc("Electrical", "Home Repair & Maintenance", "Electrical",
         "Wiring, switches, fans, lights and power issues",
         "⚡", sort_order=20, popular=True, risk=RISK_HIGH,
         required_certification=None,
         required_skills=["Electrical", "Basic wiring"],
         base_price=299, max_price=1499,
         required_equipment=["Insulated tools", "Multimeter", "Test lamp", "MCB tester"],
         possible_parts=["Switch module", "Socket", "MCB", "Wire coil", "Ceiling fan capacitor", "LED driver"],
         keywords=["spark", "shock", "switch", "socket", "fan", "light", "wiring", "power", "trip", "mcb", "short circuit"],
         assets=["Electrical wiring", "Fan", "Lighting"]),
    _svc("Carpentry", "Home Repair & Maintenance", "Carpentry",
         "Furniture, doors, shelves and woodwork",
         "🔨", sort_order=30, popular=True, risk=RISK_MEDIUM,
         base_price=349, max_price=1999,
         required_equipment=["Drill machine", "Saw", "Chisel set", "Measuring tape"],
         possible_parts=["Hinges", "Drawer channel", "Wood screws", "Laminates", "Door lock"],
         keywords=["door", "hinge", "drawer", "shelf", "wood", "cupboard", "wardrobe", "lock", "bed"],
         assets=["Furniture", "Door"]),
    _svc("Painter", "Home Repair & Maintenance", "Painting",
         "Interior and exterior wall painting, touch-ups and texture finishes",
         "🎨", duration="1–3 days", pricing_model="PER_SQFT", base_price=18, min_price=12, max_price=45,
         sort_order=40, risk=RISK_MEDIUM,
         required_equipment=["Rollers", "Brushes", "Drop sheets", "Ladder"],
         possible_parts=["Emulsion paint", "Primer", "Putty", "Masking tape"],
         keywords=["paint", "wall colour", "texture", "distemper", "putty", "touch up"],
         assets=["Wall"]),
    _svc("Mason", "Home Repair & Maintenance", "Masonry",
         "Brickwork, plaster, small civil repairs and floor levelling",
         "🧱", duration="2–8 hours", pricing_model="PER_SQFT", base_price=45, min_price=30, max_price=120,
         sort_order=45, risk=RISK_HIGH,
         required_equipment=["Trowel", "Mixing tub", "Level", "Hammer"],
         possible_parts=["Cement", "Sand", "Plaster of Paris", "Bricks"],
         keywords=["wall crack", "plaster", "cement", "brick", "grill fixing", "floor"],
         assets=["Wall", "Floor"]),
    _svc("Waterproofing", "Home Repair & Maintenance", "Waterproofing",
         "Terrace, bathroom and wall seepage treatment with warranty-backed coatings",
         "🛡️", duration="1–2 days", pricing_model="PER_SQFT", base_price=55, min_price=35, max_price=140,
         sort_order=50, risk=RISK_HIGH,
         required_skills=["Waterproofing", "Seepage treatment"],
         required_equipment=["Grinder", "Mixing drill", "Applicator rollers"],
         possible_parts=["PU sealant", "Cementitious coating", "Grouting compound", "Silicone sealant"],
         keywords=["seepage", "damp", "leakage", "ceiling leak", "waterproof", "terrace", "mould", "dampness"],
         assets=["Terrace", "Bathroom", "Wall"]),
    _svc("Tile Repair", "Home Repair & Maintenance", "Tiling",
         "Broken tile replacement, re-grouting and skirting work",
         "◻️", duration="2–6 hours", pricing_model="PER_SQFT", base_price=60, min_price=40, max_price=150,
         sort_order=55, risk=RISK_MEDIUM,
         required_equipment=["Tile cutter", "Notched trowel", "Rubber mallet", "Grout float"],
         possible_parts=["Ceramic tiles", "Tile adhesive", "Grout", "Spacers"],
         keywords=["tile", "grout", "floor tile", "skirting", "hollow tile"],
         assets=["Floor", "Wall"]),
    _svc("False Ceiling", "Home Repair & Maintenance", "False ceiling",
         "Gypsum and PVC false ceiling installation, repair and light cut-outs",
         "🏠", duration="1–3 days", pricing_model="PER_SQFT", base_price=85, min_price=55, max_price=220,
         sort_order=60, risk=RISK_HIGH,
         required_equipment=["Screw gun", "Ladder", "Chalk line", "Cutter"],
         possible_parts=["Gypsum board", "GI channel", "Anchor fasteners", "Jointing compound"],
         keywords=["false ceiling", "gypsum", "pop", "ceiling panel", "ceiling light"],
         assets=["Ceiling"]),
    _svc("Welding", "Home Repair & Maintenance", "Welding",
         "Iron gate, grill, railing and MS fabrication repairs",
         "🔥", duration="1–4 hours", pricing_model="PER_VISIT", base_price=499, min_price=349, max_price=2999,
         sort_order=65, risk=RISK_HIGH, required_certification="Arc welding safety certificate",
         required_equipment=["Arc welding set", "Face shield", "Grinder", "Gloves"],
         possible_parts=["MS rod", "Electrodes", "Hinges", "Primer"],
         keywords=["weld", "grill", "gate", "railing", "fabrication", "iron"],
         assets=["Gate", "Grill"]),
    _svc("Door & Window Repair", "Home Repair & Maintenance", "Doors and windows",
         "Alignment, hinges, sliders, glazing and mesh replacement",
         "🚪", duration="60–120 min", pricing_model="VISIT_PLUS_WORK", base_price=299, max_price=1999,
         sort_order=70, risk=RISK_MEDIUM,
         required_equipment=["Drill", "Screwdriver set", "Spirit level"],
         possible_parts=["Hinges", "Sliding wheels", "Mesh roll", "Glass pane", "Tower bolt"],
         keywords=["window", "slider", "mesh", "glass", "hinge", "window stuck"],
         assets=["Door", "Window"]),
    _svc("Furniture Assembly", "Home Repair & Maintenance", "Furniture assembly",
         "Flat-pack wardrobe, bed, table and office chair assembly",
         "🪑", duration="60–120 min", pricing_model="PER_VISIT", base_price=399, min_price=249, max_price=1499,
         sort_order=75, risk=RISK_LOW, allowed_provider_types=PROVIDER_TYPE_ANY,
         required_equipment=["Allen key set", "Power drill", "Screwdriver set"],
         possible_parts=["Cam locks", "Dowel pins", "Wood screws", "Brackets"],
         keywords=["assemble", "flat pack", "ikea", "wardrobe", "study table", "bed frame"],
         assets=["Furniture"]),
    _svc("Handyman", "Home Repair & Maintenance", "General handyman",
         "Small multi-task fixes around the house in a single visit",
         "🧰", duration="60–120 min", pricing_model="PER_VISIT", base_price=299, min_price=199, max_price=999,
         sort_order=80, risk=RISK_LOW, popular=True,
         required_equipment=["General tool kit", "Drill", "Adhesives"],
         possible_parts=["Screws", "Wall plugs", "Adhesive", "Hooks"],
         keywords=["odd job", "fix", "handyman", "small repair", "hang", "mount"],
         assets=["Household"]),

    # ================= APPLIANCE & ELECTRONICS ============================
    _svc("AC Service & Repair", "Appliance & Electronics", "Air conditioner",
         "Split/window AC service, gas refill, cooling and error-code repair",
         "❄️", duration="60–120 min", pricing_model="VISIT_PLUS_PARTS", base_price=499, min_price=349, max_price=4999,
         sort_order=110, popular=True, risk=RISK_MEDIUM,
         required_equipment=["Vacuum pump", "Gauge manifold", "Multimeter", "Jet pump"],
         possible_parts=["R32 refrigerant", "Run capacitor", "PCB board", "Fan motor", "Air filter", "Compressor"],
         keywords=["ac", "cooling", "not cooling", "gas", "refrigerant", "compressor", "water leaking ac", "noise ac", "service ac"],
         assets=["Air conditioner"]),
    _svc("Refrigerator Repair", "Appliance & Electronics", "Refrigerator",
         "Single/double door and side-by-side refrigerator repair",
         "🧊", duration="60–120 min", pricing_model="VISIT_PLUS_PARTS", base_price=449, min_price=299, max_price=5999,
         sort_order=120, risk=RISK_MEDIUM, popular=True,
         required_equipment=["Multimeter", "Clamp meter", "Vacuum pump", "Tube cutter"],
         possible_parts=["Thermostat", "Compressor relay", "Defrost timer", "Door gasket", "Gas charge", "PCB"],
         keywords=["fridge", "refrigerator", "not cooling", "freezer", "ice build up", "compressor", "water in fridge"],
         assets=["Refrigerator"]),
    _svc("Washing Machine Repair", "Appliance & Electronics", "Washing machine",
         "Top/front load washing machine drainage, spin and control faults",
         "🌀", duration="60–120 min", pricing_model="VISIT_PLUS_PARTS", base_price=449, min_price=299, max_price=4999,
         sort_order=130, risk=RISK_MEDIUM, popular=True,
         required_equipment=["Multimeter", "Screwdriver set", "Plier set", "Drain hose kit"],
         possible_parts=["Drain pump", "Inlet valve", "Belt", "Coupling", "Timer/PCB", "Door lock"],
         keywords=["washing machine", "not draining", "not spinning", "noise", "water not filling", "drum"],
         assets=["Washing machine"]),
    _svc("Microwave Repair", "Appliance & Electronics", "Microwave",
         "Microwave heating, turntable and magnetron faults",
         "📻", duration="45–90 min", pricing_model="VISIT_PLUS_PARTS", base_price=399, min_price=249, max_price=3999,
         sort_order=140, risk=RISK_HIGH,
         required_equipment=["Multimeter", "Insulated screwdrivers", "Discharge tool"],
         possible_parts=["Magnetron", "Diode", "Transformer", "Turntable motor", "Door switch"],
         keywords=["microwave", "not heating", "spark inside", "turntable", "oven"],
         assets=["Microwave"]),
    _svc("TV Repair", "Appliance & Electronics", "Television",
         "LED/LCD TV panel, backlight, sound and smart-board repair",
         "📺", duration="60–120 min", pricing_model="VISIT_PLUS_PARTS", base_price=449, min_price=299, max_price=9999,
         sort_order=150, risk=RISK_MEDIUM,
         required_equipment=["Multimeter", "ESD strap", "Screwdriver kit", "Soldering station"],
         possible_parts=["LED backlight strip", "Power board", "T-con board", "Main board", "Speaker set"],
         keywords=["tv", "no display", "sound issue", "screen lines", "smart tv", "backlight"],
         assets=["Television"]),
    _svc("Geyser Repair", "Appliance & Electronics", "Water heater",
         "Geyser heating element, thermostat and leakage repair",
         "🚿", duration="60–90 min", pricing_model="VISIT_PLUS_PARTS", base_price=399, min_price=249, max_price=3999,
         sort_order=160, risk=RISK_HIGH,
         required_equipment=["Multimeter", "Pipe wrench", "Teflon tape", "Bucket"],
         possible_parts=["Heating element", "Thermostat", "Safety valve", "Magnesium anode", "Inlet pipe"],
         keywords=["geyser", "water heater", "no hot water", "heater leaking", "thermostat"],
         assets=["Geyser"]),
    _svc("Water Purifier Service", "Appliance & Electronics", "Water purifier",
         "RO/UV purifier service, filter replacement and TDS correction",
         "💧", duration="45–90 min", pricing_model="VISIT_PLUS_PARTS", base_price=399, min_price=249, max_price=2999,
         sort_order=170, risk=RISK_MEDIUM, popular=True,
         required_equipment=["TDS meter", "Filter wrench", "Tubing cutter"],
         possible_parts=["Sediment filter", "Carbon filter", "RO membrane", "UV lamp", "Diverter valve"],
         keywords=["water purifier", "ro", "tds", "filter change", "purifier leaking", "uv"],
         assets=["Water purifier"]),
    _svc("Chimney Service", "Appliance & Electronics", "Kitchen chimney",
         "Chimney deep cleaning, suction loss and motor repair",
         "🌫️", duration="60–120 min", pricing_model="VISIT_PLUS_PARTS", base_price=499, min_price=349, max_price=2999,
         sort_order=180, risk=RISK_MEDIUM,
         required_equipment=["Degreaser", "Steam cleaner", "Screwdriver kit"],
         possible_parts=["Baffle filter", "Oil collector", "Motor capacitor", "Blower wheel"],
         keywords=["chimney", "kitchen chimney", "suction", "oil", "smoke from chimney"],
         assets=["Chimney"]),
    _svc("Hob & Stove Repair", "Appliance & Electronics", "Kitchen hob",
         "Gas hob burner, ignition and leakage repair",
         "🍳", duration="45–90 min", pricing_model="VISIT_PLUS_PARTS", base_price=349, min_price=249, max_price=1999,
         sort_order=190, risk=RISK_HIGH, required_certification="Gas appliance safety training",
         required_equipment=["Leak detector spray", "Burner tools", "Pressure gauge"],
         possible_parts=["Burner cap", "Ignition spark plug", "Gas hose", "Regulator", "Knob"],
         keywords=["gas stove", "hob", "burner", "ignition", "gas smell", "flame"],
         assets=["Kitchen hob"]),
    _svc("Air Cooler Repair", "Appliance & Electronics", "Air cooler",
         "Cooler pump, motor and cooling pad service",
         "🌬️", duration="45–90 min", pricing_model="VISIT_PLUS_PARTS", base_price=349, min_price=249, max_price=1999,
         sort_order=200, risk=RISK_LOW,
         required_equipment=["Screwdriver set", "Multimeter", "Water bucket"],
         possible_parts=["Water pump", "Cooling pad", "Fan blade", "Motor capacitor"],
         keywords=["cooler", "air cooler", "cooling pads", "cooler pump", "fan not working"],
         assets=["Air cooler"]),
    _svc("Laptop Repair", "Appliance & Electronics", "Laptop",
         "Laptop hardware, screen, battery, keyboard and OS troubleshooting",
         "💻", duration="60–180 min", pricing_model="VISIT_PLUS_PARTS", base_price=399, min_price=249, max_price=8999,
         sort_order=210, popular=True, risk=RISK_MEDIUM,
         required_equipment=["Precision screwdriver kit", "Anti-static mat", "Thermal paste"],
         possible_parts=["Battery", "Display panel", "Keyboard", "SSD", "RAM", "Thermal paste", "Hinge"],
         keywords=["laptop", "not charging", "battery", "keyboard", "screen", "overheating", "slow", "windows"],
         assets=["Laptop"]),
    _svc("Computer Repair", "Appliance & Electronics", "Desktop computer",
         "Desktop assembly, upgrades, power and performance issues",
         "🖥️", duration="60–180 min", pricing_model="VISIT_PLUS_PARTS", base_price=399, min_price=249, max_price=7999,
         sort_order=220, risk=RISK_MEDIUM,
         required_equipment=["Screwdriver kit", "Anti-static wrist strap", "Diagnostic USB"],
         possible_parts=["SMPS", "RAM", "SSD", "CPU cooler", "Motherboard", "Cables"],
         keywords=["desktop", "computer", "not booting", "smps", "restarting", "blue screen"],
         assets=["Desktop computer"]),
    _svc("Printer Repair", "Appliance & Electronics", "Printer",
         "Inkjet/laser printer, scanner and cartridge issues",
         "🖨️", duration="45–120 min", pricing_model="VISIT_PLUS_PARTS", base_price=349, min_price=249, max_price=3999,
         sort_order=230, risk=RISK_LOW,
         required_equipment=["Cleaning kit", "Screwdriver set", "Multimeter"],
         possible_parts=["Cartridge", "Roller", "Fuser unit", "Print head", "USB cable"],
         keywords=["printer", "cartridge", "paper jam", "scan", "not printing"],
         assets=["Printer"]),
    _svc("CCTV Installation & Repair", "Appliance & Electronics", "CCTV",
         "Camera, DVR/NVR installation, wiring and remote viewing setup",
         "🎥", duration="2–6 hours", pricing_model="PER_POINT", base_price=599, min_price=399, max_price=2999,
         sort_order=240, risk=RISK_HIGH, allowed_provider_types=PROVIDER_TYPE_PROFESSIONAL,
         required_equipment=["Drill", "Crimping tool", "Cable tester", "Ladder"],
         possible_parts=["IP camera", "BNC connector", "CAT6 cable", "DVR", "SMPS", "Hard disk"],
         keywords=["cctv", "camera", "security", "dvr", "nvr", "surveillance"],
         assets=["CCTV system"]),
    _svc("Wi-Fi & Network Setup", "Appliance & Electronics", "Networking",
         "Router setup, dead-zone fixes, mesh Wi-Fi and cabling",
         "📶", duration="45–120 min", pricing_model="PER_VISIT", base_price=299, min_price=199, max_price=1999,
         sort_order=250, risk=RISK_LOW,
         required_equipment=["Laptop", "LAN tester", "Crimping tool", "Drill for conduit"],
         possible_parts=["Router", "Mesh node", "CAT6 cable", "RJ45 connectors", "Repeater"],
         keywords=["wifi", "internet", "router", "slow internet", "network", "mesh", "ethernet"],
         assets=["Router", "Network"]),
    _svc("Smart Home Installation", "Appliance & Electronics", "Smart home",
         "Smart switches, video doorbells, locks and automation setup",
         "🏡", duration="2–5 hours", pricing_model="PER_POINT", base_price=499, min_price=349, max_price=4999,
         sort_order=260, risk=RISK_HIGH, allowed_provider_types=PROVIDER_TYPE_PROFESSIONAL,
         required_equipment=["Drill", "Multimeter", "Smartphone app access", "Neutral wire tester"],
         possible_parts=["Smart switch", "Video doorbell", "Smart lock", "Hub", "Sensors"],
         keywords=["smart home", "smart switch", "doorbell", "alexa", "google home", "automation"],
         assets=["Smart device"]),

    # ================= CLEANING & PEST CONTROL ============================
    _svc("Cleaning", "Cleaning & Pest Control", "Home cleaning",
         "Home, kitchen, bathroom and office cleaning",
         "🧹", duration="2–5 hours", pricing_model="PER_BHK", base_price=399, min_price=299, max_price=2499,
         sort_order=310, popular=True, risk=RISK_LOW,
         required_equipment=["Vacuum cleaner", "Microfibre mops", "Cleaning chemicals", "Gloves"],
         possible_parts=["Floor cleaner", "Glass cleaner", "Scrub pads", "Trash liners"],
         keywords=["cleaning", "clean home", "dusting", "mopping", "housekeeping"],
         assets=["Household"]),
    _svc("Full Home Deep Cleaning", "Cleaning & Pest Control", "Deep cleaning",
         "Top-to-bottom deep cleaning with machine scrubbing",
         "✨", duration="4–8 hours", pricing_model="PER_BHK", base_price=1299, min_price=899, max_price=8999,
         sort_order=320, popular=True, risk=RISK_LOW,
         required_equipment=["Single-disc scrubber", "Vacuum cleaner", "Steam cleaner", "Ladders"],
         possible_parts=["Deep-clean chemicals", "Degreaser", "Descaling gel"],
         keywords=["deep cleaning", "full home cleaning", "machine cleaning", "move in cleaning"],
         assets=["Household"]),
    _svc("Bathroom Cleaning", "Cleaning & Pest Control", "Bathroom cleaning",
         "Hard-water stain removal, descaling and sanitisation",
         "🛁", duration="60–120 min", pricing_model="PER_UNIT", base_price=349, min_price=249, max_price=1299,
         sort_order=330, risk=RISK_LOW,
         required_equipment=["Descaling chemicals", "Scrub brush set", "Sprayer"],
         possible_parts=["Descaling gel", "Toilet cleaner", "Grout cleaner"],
         keywords=["bathroom", "toilet cleaning", "hard water", "tap stains"],
         assets=["Bathroom"]),
    _svc("Kitchen Cleaning", "Cleaning & Pest Control", "Kitchen cleaning",
         "Degreasing of chimney, hob, cabinets and tiles",
         "🍽️", duration="2–4 hours", pricing_model="PER_UNIT", base_price=599, min_price=399, max_price=2499,
         sort_order=340, risk=RISK_LOW,
         required_equipment=["Degreaser", "Steam cleaner", "Scrub pads"],
         possible_parts=["Kitchen degreaser", "Hob cleaner"],
         keywords=["kitchen cleaning", "degreasing", "oil stains", "cabinet cleaning"],
         assets=["Kitchen"]),
    _svc("Sofa Cleaning", "Cleaning & Pest Control", "Upholstery cleaning",
         "Shampoo, extraction and stain removal for sofas",
         "🛋️", duration="60–150 min", pricing_model="PER_SEAT", base_price=449, min_price=299, max_price=1499,
         sort_order=350, risk=RISK_LOW,
         required_equipment=["Shampoo extractor", "Upholstery brush", "Vacuum"],
         possible_parts=["Upholstery shampoo", "Stain remover"],
         keywords=["sofa cleaning", "couch", "fabric cleaning", "stain removal"],
         assets=["Sofa"]),
    _svc("Carpet Cleaning", "Cleaning & Pest Control", "Carpet cleaning",
         "Carpet shampooing, extraction and deodorising",
         "🧽", duration="60–150 min", pricing_model="PER_SQFT", base_price=15, min_price=8, max_price=40,
         sort_order=360, risk=RISK_LOW,
         required_equipment=["Extraction machine", "Carpet brush", "Vacuum"],
         possible_parts=["Carpet shampoo", "Deodoriser"],
         keywords=["carpet cleaning", "rug", "shampoo", "odour"],
         assets=["Carpet"]),
    _svc("Mattress Cleaning", "Cleaning & Pest Control", "Mattress cleaning",
         "Vacuuming, UV sanitisation and deep stain treatment",
         "🛏️", duration="45–90 min", pricing_model="PER_UNIT", base_price=399, min_price=249, max_price=1299,
         sort_order=370, risk=RISK_LOW,
         required_equipment=["Vacuum with HEPA", "UV sanitiser", "Steam unit"],
         possible_parts=["Mattress shampoo", "Anti-allergen spray"],
         keywords=["mattress", "dust mites", "bed cleaning", "allergy"],
         assets=["Mattress"]),
    _svc("Water Tank Cleaning", "Cleaning & Pest Control", "Water tank cleaning",
         "Tank de-sludging, chlorination and disinfection",
         "🚰", duration="2–4 hours", pricing_model="PER_UNIT", base_price=899, min_price=599, max_price=4999,
         sort_order=380, risk=RISK_MEDIUM,
         required_equipment=["Submersible pump", "Scrubbing brushes", "Chlorination kit", "Safety harness"],
         possible_parts=["Bleaching powder", "Chlorine tablets", "Sealant"],
         keywords=["water tank", "tank cleaning", "overhead tank", "sludge"],
         assets=["Water tank"]),
    _svc("Move In / Move Out Cleaning", "Cleaning & Pest Control", "Move cleaning",
         "Complete pre/post move cleaning with appliance interiors",
         "📦", duration="4–8 hours", pricing_model="PER_BHK", base_price=1499, min_price=999, max_price=9999,
         sort_order=390, risk=RISK_LOW,
         required_equipment=["Scrubber", "Vacuum", "Ladders", "Chemicals"],
         possible_parts=["Deep-clean chemicals"],
         keywords=["move out", "move in", "vacant house cleaning", "shifting cleaning"],
         assets=["Household"]),
    _svc("Cockroach Control", "Cleaning & Pest Control", "Cockroach control",
         "Gel-based cockroach treatment safe for kitchens",
         "🪳", duration="45–90 min", pricing_model="PER_UNIT", base_price=599, min_price=449, max_price=2499,
         sort_order=400, risk=RISK_MEDIUM, required_certification="Pest control operator licence",
         allowed_provider_types=PROVIDER_TYPE_PROFESSIONAL,
         required_equipment=["Gel applicator", "PPE kit", "Sprayer"],
         possible_parts=["Cockroach gel", "Insecticide"],
         keywords=["cockroach", "pest", "insects", "kitchen pest"],
         assets=["Household"]),
    _svc("Ant Control", "Cleaning & Pest Control", "Ant control",
         "Targeted ant gel and spray treatment",
         "🐜", duration="30–60 min", pricing_model="PER_UNIT", base_price=499, min_price=349, max_price=1999,
         sort_order=410, risk=RISK_MEDIUM, required_certification="Pest control operator licence",
         allowed_provider_types=PROVIDER_TYPE_PROFESSIONAL,
         required_equipment=["Sprayer", "PPE kit", "Gel applicator"],
         possible_parts=["Ant gel", "Insecticide"],
         keywords=["ants", "ant control", "pest"],
         assets=["Household"]),
    _svc("Bed Bug Control", "Cleaning & Pest Control", "Bed bug control",
         "Multi-visit bed bug treatment with follow-up inspection",
         "🛌", duration="2–3 hours", pricing_model="PER_UNIT", base_price=1499, min_price=999, max_price=6999,
         sort_order=420, risk=RISK_HIGH, required_certification="Pest control operator licence",
         allowed_provider_types=PROVIDER_TYPE_PROFESSIONAL,
         required_equipment=["Steam unit", "Residual sprayer", "PPE kit", "Mattress encasements"],
         possible_parts=["Residual insecticide", "Diatomaceous earth"],
         keywords=["bed bugs", "bites", "mattress bugs", "pest"],
         assets=["Mattress", "Bed"]),
    _svc("Termite Control", "Cleaning & Pest Control", "Termite control",
         "Drill-fill-seal anti-termite treatment with warranty",
         "🪵", duration="3–8 hours", pricing_model="PER_SQFT", base_price=14, min_price=9, max_price=35,
         sort_order=430, risk=RISK_HIGH, required_certification="Pest control operator licence",
         allowed_provider_types=PROVIDER_TYPE_PROFESSIONAL,
         required_equipment=["Drill machine", "Injection pump", "PPE kit", "Borer"],
         possible_parts=["Termiticide concentrate", "Sealant"],
         keywords=["termite", "wood borer", "termites", "furniture damage"],
         assets=["Household", "Furniture"]),
    _svc("Mosquito Control", "Cleaning & Pest Control", "Mosquito control",
         "Indoor/outdoor fogging and larvicidal treatment",
         "🦟", duration="45–120 min", pricing_model="PER_UNIT", base_price=499, min_price=349, max_price=2999,
         sort_order=440, risk=RISK_MEDIUM, required_certification="Pest control operator licence",
         allowed_provider_types=PROVIDER_TYPE_PROFESSIONAL,
         required_equipment=["Fogging machine", "Sprayer", "PPE kit", "Larvicide"],
         possible_parts=["Larvicide", "Fogging solution"],
         keywords=["mosquito", "fogging", "dengue", "malaria"],
         assets=["Household"]),
    _svc("General Pest Control", "Cleaning & Pest Control", "General pest control",
         "Combined treatment for common household pests",
         "🐛", duration="1–2 hours", pricing_model="PER_UNIT", base_price=699, min_price=499, max_price=2999,
         sort_order=450, popular=True, risk=RISK_MEDIUM,
         required_certification="Pest control operator licence",
         allowed_provider_types=PROVIDER_TYPE_PROFESSIONAL,
         required_equipment=["Sprayer", "PPE kit", "Gel applicator"],
         possible_parts=["Insecticide", "Gel bait", "Glue traps"],
         keywords=["pest control", "spiders", "lizards", "rodents", "rats"],
         assets=["Household"]),
    _svc("Disinfection Service", "Cleaning & Pest Control", "Disinfection",
         "Hospital-grade sanitisation for homes and offices",
         "🧴", duration="45–120 min", pricing_model="PER_SQFT", base_price=3, min_price=2, max_price=12,
         sort_order=460, risk=RISK_MEDIUM,
         required_certification="Chemical handling safety training",
         allowed_provider_types=PROVIDER_TYPE_PROFESSIONAL,
         required_equipment=["ULV fogger", "PPE kit", "Sanitiser"],
         possible_parts=["Disinfectant concentrate"],
         keywords=["disinfection", "sanitisation", "covid", "fumigation"],
         assets=["Household"]),

    # ================= BEAUTY & PERSONAL CARE =============================
    _svc("Women's Salon at Home", "Beauty & Personal Care", "Salon at home",
         "Complete salon package for women at home",
         "💅", duration="60–180 min", pricing_model="PER_PACKAGE", base_price=899, min_price=599, max_price=5999,
         sort_order=510, popular=True, risk=RISK_LOW,
         required_skills=["Beauty therapy", "Women's salon"],
         required_equipment=["Salon kit", "Sterilised tools", "Products set"],
         possible_parts=["Wax", "Facial kit", "Hair products"],
         keywords=["salon", "women salon", "beauty", "home salon"],
         assets=[]),
    _svc("Men's Salon at Home", "Beauty & Personal Care", "Salon at home",
         "Barber-style grooming and men's salon services at home",
         "💈", duration="45–120 min", pricing_model="PER_PACKAGE", base_price=499, min_price=299, max_price=2999,
         sort_order=520, popular=True, risk=RISK_LOW,
         required_skills=["Barbering", "Men's grooming"],
         required_equipment=["Trimmer", "Scissors set", "Sterilisation kit"],
         possible_parts=["Shaving gel", "After-shave", "Hair products"],
         keywords=["mens salon", "barber", "grooming", "beard"],
         assets=[]),
    _svc("Haircut", "Beauty & Personal Care", "Haircut",
         "Precision haircut and styling at home",
         "✂️", duration="30–60 min", pricing_model="PER_VISIT", base_price=249, min_price=149, max_price=999,
         sort_order=530, risk=RISK_LOW,
         required_skills=["Haircut", "Hair styling"],
         required_equipment=["Clippers", "Scissors", "Cape", "Sanitiser"],
         possible_parts=["Hair products"],
         keywords=["haircut", "hair cut", "trim", "fade"],
         assets=[]),
    _svc("Hair Styling", "Beauty & Personal Care", "Hair styling",
         "Blow-dry, curls, straightening and party styling",
         "💫", duration="45–120 min", pricing_model="PER_SERVICE", base_price=499, min_price=299, max_price=3999,
         sort_order=540, risk=RISK_LOW,
         required_skills=["Hair styling", "Hair treatment"],
         required_equipment=["Dryer", "Straightener", "Curler", "Heat protectant"],
         possible_parts=["Styling products", "Serum"],
         keywords=["hair styling", "blow dry", "curls", "straightening"],
         assets=[]),
    _svc("Makeup Artist", "Beauty & Personal Care", "Makeup",
         "Professional makeup for parties and events",
         "💄", duration="60–150 min", pricing_model="PER_SERVICE", base_price=1499, min_price=999, max_price=9999,
         sort_order=550, risk=RISK_LOW,
         required_skills=["Makeup", "Beauty therapy"],
         required_equipment=["Professional makeup kit", "Sanitised brushes", "Mirror", "Lighting"],
         possible_parts=["Foundation", "Setting spray"],
         keywords=["makeup", "artist", "party makeup", "glam"],
         assets=[]),
    _svc("Bridal Makeup", "Beauty & Personal Care", "Bridal",
         "Bridal makeup with draping, hair and trial session",
         "👰", duration="3–6 hours", pricing_model="PER_PACKAGE", base_price=8999, min_price=4999, max_price=49999,
         sort_order=560, risk=RISK_LOW,
         required_skills=["Bridal makeup", "Hair styling"],
         required_equipment=["HD makeup kit", "Draping materials", "Steamer", "Lighting"],
         possible_parts=["HD makeup kit", "Draping accessories"],
         keywords=["bridal", "wedding makeup", "dulhan", "bride"],
         assets=[]),
    _svc("Mehendi Artist", "Beauty & Personal Care", "Mehendi",
         "Traditional and designer mehendi application",
         "🪷", duration="1–4 hours", pricing_model="PER_SERVICE", base_price=899, min_price=399, max_price=14999,
         sort_order=570, risk=RISK_LOW,
         required_skills=["Mehendi", "Design work"],
         required_equipment=["Mehendi cones", "Tissue", "Aftercare balm"],
         possible_parts=["Mehendi cones", "Essential oils"],
         keywords=["mehendi", "henna", "bridal mehendi", "design"],
         assets=[]),
    _svc("Beautician", "Beauty & Personal Care", "Beauty therapy",
         "Skin and beauty treatments at home",
         "🧖", duration="60–150 min", pricing_model="PER_SERVICE", base_price=799, min_price=499, max_price=4999,
         sort_order=580, risk=RISK_LOW,
         required_skills=["Beauty therapy", "Skin treatment"],
         required_equipment=["Facial kit", "Steamer", "Massager", "Sanitised tools"],
         possible_parts=["Facial products", "Masks", "Serums"],
         keywords=["beautician", "skin", "glow", "treatment"],
         assets=[]),
    _svc("Facial", "Beauty & Personal Care", "Facial",
         "Cleansing, exfoliation and massage facial treatments",
         "😊", duration="45–90 min", pricing_model="PER_SERVICE", base_price=699, min_price=399, max_price=3999,
         sort_order=590, risk=RISK_LOW,
         required_skills=["Facial", "Skin treatment"],
         required_equipment=["Facial kit", "Steamer", "Headband", "Massage cream"],
         possible_parts=["Facial packs", "Serums"],
         keywords=["facial", "clean up", "bleach"],
         assets=[]),
    _svc("Manicure", "Beauty & Personal Care", "Nail care",
         "Nail shaping, cuticle care and polish",
         "💅", duration="40–60 min", pricing_model="PER_SERVICE", base_price=399, min_price=249, max_price=1999,
         sort_order=600, risk=RISK_LOW,
         required_skills=["Manicure", "Nail care"],
         required_equipment=["Sterilised nail kit", "Buffer", "Soak bowl"],
         possible_parts=["Nail polish", "Cuticle oil", "Base coat"],
         keywords=["manicure", "nails", "nail art"],
         assets=[]),
    _svc("Pedicure", "Beauty & Personal Care", "Nail care",
         "Foot soak, scrub, callus removal and polish",
         "🦶", duration="45–75 min", pricing_model="PER_SERVICE", base_price=499, min_price=299, max_price=1999,
         sort_order=610, risk=RISK_LOW,
         required_skills=["Pedicure", "Nail care"],
         required_equipment=["Sterilised pedicure kit", "Foot scraper", "Soak tub"],
         possible_parts=["Foot scrub", "Nail polish", "Callus remover"],
         keywords=["pedicure", "foot care", "callus"],
         assets=[]),
    _svc("Waxing", "Beauty & Personal Care", "Hair removal",
         "Full body, half body or targeted waxing at home",
         "🕯️", duration="30–90 min", pricing_model="PER_SERVICE", base_price=599, min_price=299, max_price=2999,
         sort_order=620, risk=RISK_LOW,
         required_skills=["Waxing", "Hair removal"],
         required_equipment=["Wax warmer", "Disposable spatulas", "Strips"],
         possible_parts=["Wax", "Pre/post care lotion"],
         keywords=["waxing", "wax", "hair removal", "full body wax"],
         assets=[]),
    _svc("Spa & Massage at Home", "Beauty & Personal Care", "Wellness",
         "Relaxation massage and spa therapies at home (non-medical)",
         "🧘", duration="60–120 min", pricing_model="PER_SESSION", base_price=1499, min_price=899, max_price=6999,
         sort_order=630, risk=RISK_MEDIUM,
         required_skills=["Massage therapy", "Spa therapy"],
         required_certification="Massage therapy training certificate",
         required_equipment=["Massage table", "Oils", "Towels", "Candles"],
         possible_parts=["Massage oil", "Aromatherapy oil"],
         keywords=["spa", "massage", "relax", "therapy"],
         assets=[]),

    # ================= HOME IMPROVEMENT ===================================
    _svc("Wall Décor & Wall Panels", "Home Improvement", "Wall décor",
         "Feature walls, wallpaper, PVC panels and wall art installation",
         "🖼️", duration="3–8 hours", pricing_model="PER_SQFT", base_price=95, min_price=60, max_price=350,
         sort_order=710, risk=RISK_MEDIUM,
         required_equipment=["Drill", "Laser level", "Adhesive gun", "Cutting tools"],
         possible_parts=["Wallpaper", "PVC panel", "WPC louver", "Adhesive"],
         keywords=["wall decor", "wallpaper", "wall panel", "accent wall", "louvers"],
         assets=["Wall"]),
    _svc("Furniture Installation", "Home Improvement", "Furniture fitting",
         "Modular kitchen, wardrobe and TV unit installation",
         "🛠️", duration="3–10 hours", pricing_model="PER_VISIT", base_price=999, min_price=599, max_price=9999,
         sort_order=720, risk=RISK_HIGH,
         required_equipment=["Power tools", "Laser level", "Drill", "Caulking gun"],
         possible_parts=["Hinges", "Channels", "Handles", "Edge banding", "Fasteners"],
         keywords=["modular", "wardrobe install", "kitchen install", "tv unit"],
         assets=["Furniture"]),
    _svc("Curtain & Blind Installation", "Home Improvement", "Curtains",
         "Curtain rod, track and blind fitting with measurements",
         "🪟", duration="1–3 hours", pricing_model="PER_POINT", base_price=249, min_price=149, max_price=999,
         sort_order=730, risk=RISK_MEDIUM,
         required_equipment=["Drill", "Wall plugs", "Measuring tape", "Ladder"],
         possible_parts=["Curtain rod", "Brackets", "Roller blind", "Motorised track"],
         keywords=["curtain", "blind", "rod", "window covering"],
         assets=["Window"]),
    _svc("Interior Assistance", "Home Improvement", "Interior design",
         "Design consultation, layout planning and vendor coordination",
         "📐", duration="Consultation", pricing_model="PER_CONSULTATION", base_price=1999, min_price=999, max_price=24999,
         sort_order=740, risk=RISK_LOW, allowed_provider_types=PROVIDER_TYPE_PROFESSIONAL,
         required_equipment=["Measurement kit", "Design software"],
         possible_parts=["3D render", "Material samples"],
         keywords=["interior", "design", "consultant", "layout", "floor plan"],
         assets=["Household"]),
    _svc("Waterproofing & Seepage Treatment", "Home Improvement", "Waterproofing",
         "Advanced seepage diagnosis and injection grouting",
         "💦", duration="1–3 days", pricing_model="PER_SQFT", base_price=75, min_price=45, max_price=180,
         sort_order=750, risk=RISK_HIGH,
         required_skills=["Waterproofing", "Injection grouting"],
         required_certification="Waterproofing applicator training",
         required_equipment=["Injection pump", "Grinder", "Moisture meter", "PPE kit"],
         possible_parts=["PU injection resin", "Crystalline coating", "Sealant"],
         keywords=["seepage", "leakage", "damp wall", "grouting", "waterproofing"],
         assets=["Wall", "Terrace", "Bathroom"]),

    # ================= MOVING & SUPPORT ===================================
    _svc("Packers & Movers", "Moving & Support", "Packers and movers",
         "Packing, loading, transport coordination and unpacking",
         "🚚", duration="4–12 hours", pricing_model="PER_TRIP", base_price=2999, min_price=1499, max_price=49999,
         sort_order=810, risk=RISK_MEDIUM,
         required_skills=["Packers and movers", "Shifting"],
         required_equipment=["Cartons", "Bubble wrap", "Furniture blankets", "Trolley", "Tools"],
         possible_parts=["Packing material", "Stretch film", "Tape"],
         keywords=["packers", "movers", "shifting", "relocation", "moving house"],
         assets=["Household"]),
    _svc("Furniture Shifting", "Moving & Support", "Furniture shifting",
         "Single-item or room-wise furniture shifting with dismantling",
         "🛋️", duration="2–6 hours", pricing_model="PER_TRIP", base_price=999, min_price=599, max_price=9999,
         sort_order=820, risk=RISK_MEDIUM,
         required_skills=["Furniture shifting", "Packing"],
         required_equipment=["Trolley", "Straps", "Blankets", "Tools"],
         possible_parts=["Packing material", "Corner guards"],
         keywords=["furniture shifting", "move sofa", "bed shifting"],
         assets=["Furniture"]),
    _svc("Appliance Shifting", "Moving & Support", "Appliance shifting",
         "Safe uninstall, transport and reinstall of appliances",
         "🔌", duration="2–6 hours", pricing_model="PER_TRIP", base_price=1299, min_price=799, max_price=9999,
         sort_order=830, risk=RISK_HIGH,
         required_skills=["Appliance installation", "Shifting"],
         required_equipment=["Trolley", "Straps", "Tool kit", "Packing material"],
         possible_parts=["Copper piping", "Stand", "Stabiliser"],
         keywords=["appliance shifting", "ac shifting", "fridge shifting", "install"],
         assets=["Air conditioner", "Refrigerator", "Washing machine"]),
    _svc("Loading & Unloading", "Moving & Support", "Labour",
         "Trained manpower for loading and unloading",
         "💪", duration="2–6 hours", pricing_model="PER_HOUR", base_price=399, min_price=249, max_price=1499,
         sort_order=840, risk=RISK_MEDIUM,
         required_skills=["Loading and unloading", "Labour"],
         required_equipment=["Hand gloves", "Straps", "Trolley"],
         possible_parts=[],
         keywords=["loading", "unloading", "labour", "helpers", "manpower"],
         assets=["Household"]),
    _svc("Local Delivery Assistance", "Moving & Support", "Delivery",
         "Local pickup, drop-off and store runs",
         "🛵", duration="30–120 min", pricing_model="PER_TRIP", base_price=149, min_price=99, max_price=1999,
         sort_order=850, risk=RISK_LOW,
         required_skills=["Delivery & Errands", "Local delivery"],
         required_equipment=["Two-wheeler or vehicle", "Helmet", "Phone mount"],
         possible_parts=[],
         keywords=["delivery", "pickup", "errand", "courier", "drop"],
         assets=[]),

    # ================= VEHICLE SERVICES ===================================
    _svc("Two-Wheeler Mechanic", "Vehicle Services", "Two-wheeler",
         "Bike/scooter service, starting trouble and brake work",
         "🏍️", duration="60–180 min", pricing_model="VISIT_PLUS_PARTS", base_price=399, min_price=249, max_price=4999,
         sort_order=910, popular=True, risk=RISK_HIGH,
         required_certification="Two-wheeler mechanic certification",
         required_equipment=["Tool kit", "Paddock stand", "Compressor", "Multimeter"],
         possible_parts=["Engine oil", "Brake pads", "Spark plug", "Chain kit", "Battery", "Clutch plates"],
         keywords=["bike", "scooter", "two wheeler", "chain", "brake", "service bike", "not starting"],
         assets=["Two-wheeler"]),
    _svc("Car Mechanic", "Vehicle Services", "Car",
         "Car periodic service, diagnostics and breakdown repair",
         "🚗", duration="2–8 hours", pricing_model="VISIT_PLUS_PARTS", base_price=999, min_price=599, max_price=24999,
         sort_order=920, risk=RISK_HIGH,
         required_certification="Automobile mechanic certification",
         required_equipment=["OBD scanner", "Jack and stands", "Tool kit", "Torque wrench"],
         possible_parts=["Engine oil", "Filters", "Brake pads", "Battery", "Belts", "Suspension parts"],
         keywords=["car", "car service", "engine", "obd", "noise", "brake", "battery"],
         assets=["Car"]),
    _svc("Battery Assistance", "Vehicle Services", "Battery",
         "Jump-start, battery testing and on-site replacement",
         "🔋", duration="30–60 min", pricing_model="PER_VISIT", base_price=299, min_price=199, max_price=2499,
         sort_order=930, risk=RISK_HIGH,
         required_certification="Battery handling safety training",
         required_equipment=["Jump-start kit", "Battery tester", "Insulated gloves", "Spanners"],
         possible_parts=["Vehicle battery", "Terminal clamps", "Fuses"],
         keywords=["battery", "jump start", "dead battery", "car not starting"],
         assets=["Car", "Two-wheeler"]),
    _svc("Tyre Service", "Vehicle Services", "Tyres",
         "Puncture repair, tyre change and wheel balancing",
         "🛞", duration="30–90 min", pricing_model="PER_TYRE", base_price=249, min_price=149, max_price=1999,
         sort_order=940, risk=RISK_HIGH,
         required_equipment=["Tyre levers", "Compressor", "Puncture kit", "Jack"],
         possible_parts=["Tyre tube", "Tyre", "Valve", "Wheel weights"],
         keywords=["tyre", "puncture", "flat tyre", "wheel", "balancing"],
         assets=["Car", "Two-wheeler"]),
    _svc("Vehicle Washing & Detailing", "Vehicle Services", "Detailing",
         "Foam wash, interior detailing and ceramic coating",
         "🧼", duration="1–4 hours", pricing_model="PER_SERVICE", base_price=499, min_price=299, max_price=8999,
         sort_order=950, risk=RISK_MEDIUM,
         required_equipment=["Pressure washer", "Foam cannon", "Vacuum", "Microfibre set", "Polisher"],
         possible_parts=["Shampoo", "Wax", "Ceramic coating", "Interior cleaner"],
         keywords=["car wash", "detailing", "foam wash", "polish", "bike wash"],
         assets=["Car", "Two-wheeler"]),
    _svc("Emergency Roadside Assistance", "Vehicle Services", "Roadside",
         "On-road breakdown support within the service radius",
         "🚨", duration="30–90 min", pricing_model="PER_VISIT", base_price=599, min_price=399, max_price=4999,
         sort_order=960, risk=RISK_HIGH,
         required_certification="Roadside assistance training",
         required_equipment=["Tow rope", "Jump-start kit", "Tool kit", "Warning triangle", "Torch"],
         possible_parts=["Fuses", "Fuel", "Coolant", "Spare tyre"],
         keywords=["roadside", "breakdown", "towing", "emergency vehicle", "stuck"],
         assets=["Car", "Two-wheeler"]),

    # ================= EDUCATION & DIGITAL ================================
    _svc("Home Tutor", "Education & Digital", "Tuition",
         "School subject tuition at home (KG–12)",
         "📚", duration="60–90 min", pricing_model="PER_MONTH", base_price=2499, min_price=1499, max_price=14999,
         sort_order=1010, risk=RISK_LOW,
         required_skills=["Home tutor", "Teaching"],
         required_equipment=["Study material", "Whiteboard", "Stationery"],
         possible_parts=[],
         keywords=["tutor", "tuition", "home tutor", "maths", "science", "school"],
         assets=[]),
    _svc("Coding Tutor", "Education & Digital", "Coding",
         "Python, web development, robotics and school coding classes",
         "👨‍💻", duration="60–120 min", pricing_model="PER_MONTH", base_price=2999, min_price=1999, max_price=19999,
         sort_order=1020, risk=RISK_LOW,
         required_skills=["Coding tutor", "Programming"],
         required_equipment=["Laptop", "Projector (optional)", "Practice environment"],
         possible_parts=[],
         keywords=["coding", "python", "programming", "web development", "scratch"],
         assets=[]),
    _svc("Computer Training", "Education & Digital", "Training",
         "MS Office, Tally, design tools and basic computer literacy",
         "🖱️", duration="60–120 min", pricing_model="PER_MONTH", base_price=1999, min_price=999, max_price=14999,
         sort_order=1030, risk=RISK_LOW,
         required_skills=["Computer training", "Teaching"],
         required_equipment=["Computer/laptop", "Training material"],
         possible_parts=[],
         keywords=["computer class", "excel", "tally", "training", "ms office"],
         assets=[]),
    _svc("Digital Assistance", "Education & Digital", "Digital help",
         "Online forms, government portals, printing and digital documentation help",
         "🧾", duration="30–120 min", pricing_model="PER_VISIT", base_price=199, min_price=99, max_price=999,
         sort_order=1040, risk=RISK_LOW,
         required_skills=["Digital assistance", "Computer support"],
         required_equipment=["Laptop", "Printer access", "Internet"],
         possible_parts=[],
         keywords=["digital", "online form", "aadhaar", "print", "scan", "documents"],
         assets=[]),
    _svc("Device Setup", "Education & Digital", "Device setup",
         "New phone, laptop or tablet setup with data transfer",
         "📱", duration="30–90 min", pricing_model="PER_VISIT", base_price=299, min_price=199, max_price=1499,
         sort_order=1050, risk=RISK_LOW,
         required_skills=["Device setup", "Mobile Repair"],
         required_equipment=["Cables", "Data transfer tools", "Screen protector kit"],
         possible_parts=["Screen guard", "Sim tool", "Cable"],
         keywords=["setup", "new phone", "data transfer", "device"],
         assets=["Laptop", "Smartphone"]),

    # ================= PET SERVICES =======================================
    _svc("Pet Grooming", "Pet Services", "Grooming",
         "Bath, trim, nail clipping and de-shedding at home",
         "🐕", duration="60–120 min", pricing_model="PER_SERVICE", base_price=899, min_price=599, max_price=3999,
         sort_order=1110, popular=True, risk=RISK_MEDIUM,
         required_skills=["Pet grooming", "Animal handling"],
         required_equipment=["Pet clipper", "Dryer", "Pet shampoo", "Nail clipper"],
         possible_parts=["Pet shampoo", "Coat conditioner", "Tick treatment"],
         keywords=["pet grooming", "dog bath", "grooming", "nail trim"],
         assets=[]),
    _svc("Pet Walking", "Pet Services", "Walking",
         "Daily or one-time dog walking with GPS-checked updates",
         "🐾", duration="30–60 min", pricing_model="PER_WALK", base_price=199, min_price=99, max_price=599,
         sort_order=1120, risk=RISK_LOW,
         required_skills=["Pet walking", "Animal handling"],
         required_equipment=["Leash", "Waste bags", "Water bottle"],
         possible_parts=[],
         keywords=["dog walking", "pet walk", "walk dog"],
         assets=[]),
    _svc("Pet Sitting", "Pet Services", "Sitting",
         "Feeding, play and companionship visits while you are away",
         "🏠", duration="30–180 min", pricing_model="PER_VISIT", base_price=399, min_price=249, max_price=1999,
         sort_order=1130, risk=RISK_MEDIUM,
         required_skills=["Pet sitting", "Animal handling"],
         required_equipment=["Feeding bowls", "Cleaning supplies", "Pet first-aid kit"],
         possible_parts=[],
         keywords=["pet sitting", "cat sitting", "pet care", "daycare"],
         assets=[]),
    _svc("Basic Pet Care Assistance", "Pet Services", "Care",
         "Vet-visit accompaniment, medication support and feeding help",
         "🩺", duration="60–180 min", pricing_model="PER_VISIT", base_price=499, min_price=299, max_price=2499,
         sort_order=1140, risk=RISK_MEDIUM,
         required_skills=["Pet care", "Animal handling"],
         required_certification="Pet first-aid training",
         required_equipment=["Pet carrier", "First-aid kit", "Sanitiser"],
         possible_parts=["Pet supplements"],
         keywords=["pet care", "medication", "vet visit", "pet health"],
         assets=[]),
]

# ---------------------------------------------------------------------------
# Legacy V9.3 rows -> V10 metadata enrichment.
# Existing rows keep their ids/names; we only add category metadata so that
# historical requests, providers and pricing continue to work unchanged.
# ---------------------------------------------------------------------------
LEGACY_SERVICE_METADATA = {
    "Appliance Repair": {
        "subcategory": "Home appliance",
        "risk_level": RISK_MEDIUM,
        "estimated_duration": "60–120 min",
        "pricing_model": "VISIT_PLUS_PARTS",
    },
    "Mobile Repair": {
        "subcategory": "Mobile phone",
        "risk_level": RISK_MEDIUM,
        "estimated_duration": "45–120 min",
        "pricing_model": "VISIT_PLUS_PARTS",
    },
    "Basic IT Support": {
        "subcategory": "IT support",
        "risk_level": RISK_LOW,
        "estimated_duration": "45–120 min",
        "pricing_model": "PER_VISIT",
    },
    "Delivery & Errands": {
        "subcategory": "Delivery",
        "risk_level": RISK_LOW,
        "estimated_duration": "30–120 min",
        "pricing_model": "PER_TRIP",
    },
}

# ---------------------------------------------------------------------------
# Asset types (Module 1 — Service Passport)
# ---------------------------------------------------------------------------
ASSET_TYPES = [
    ("Air conditioner", "Appliance & Electronics", "❄️"),
    ("Refrigerator", "Appliance & Electronics", "🧊"),
    ("Washing machine", "Appliance & Electronics", "🌀"),
    ("Television", "Appliance & Electronics", "📺"),
    ("Microwave", "Appliance & Electronics", "📻"),
    ("Water purifier", "Appliance & Electronics", "💧"),
    ("Geyser", "Appliance & Electronics", "🚿"),
    ("Laptop", "Appliance & Electronics", "💻"),
    ("Desktop computer", "Appliance & Electronics", "🖥️"),
    ("Smartphone", "Appliance & Electronics", "📱"),
    ("Printer", "Appliance & Electronics", "🖨️"),
    ("Chimney", "Appliance & Electronics", "🌫️"),
    ("Kitchen hob", "Appliance & Electronics", "🍳"),
    ("Air cooler", "Appliance & Electronics", "🌬️"),
    ("Electrical wiring", "Home Repair & Maintenance", "⚡"),
    ("Lighting", "Home Repair & Maintenance", "💡"),
    ("Fan", "Home Repair & Maintenance", "🌀"),
    ("Furniture", "Home Repair & Maintenance", "🪑"),
    ("Door", "Home Repair & Maintenance", "🚪"),
    ("Window", "Home Repair & Maintenance", "🪟"),
    ("Wall", "Home Repair & Maintenance", "🧱"),
    ("Ceiling", "Home Repair & Maintenance", "🏠"),
    ("Bathroom", "Home Repair & Maintenance", "🛁"),
    ("Kitchen", "Home Repair & Maintenance", "🍽️"),
    ("Water tank", "Home Repair & Maintenance", "🚰"),
    ("Sofa", "Cleaning & Pest Control", "🛋️"),
    ("Mattress", "Cleaning & Pest Control", "🛏️"),
    ("Carpet", "Cleaning & Pest Control", "🧽"),
    ("CCTV system", "Appliance & Electronics", "🎥"),
    ("Router", "Appliance & Electronics", "📶"),
    ("Smart device", "Appliance & Electronics", "🏡"),
    ("Two-wheeler", "Vehicle Services", "🏍️"),
    ("Car", "Vehicle Services", "🚗"),
    ("Solar system", "Home Repair & Maintenance", "☀️"),
    ("Inverter & battery", "Home Repair & Maintenance", "🔋"),
    ("Other asset", "Home Repair & Maintenance", "📦"),
]

# ---------------------------------------------------------------------------
# Mission decomposition templates (Module 2 fallback when AI is offline)
# ---------------------------------------------------------------------------
MISSION_TEMPLATES = [
    {
        "key": "water_leak_and_electrical",
        "match": ["leak", "seepage", "damp", "spark", "shock", "electrical", "water"],
        "title": "Water leakage with electrical safety concern",
        "tasks": [
            ("Electrical safety inspection", "Electrical", "Isolate and test the affected circuit before any wet work.", 1),
            ("Leak source detection & plumbing repair", "Plumbing", "Trace the leak, repair the pipe/joint and stop the water ingress.", 1),
            ("Seepage / waterproofing treatment", "Waterproofing", "Treat the affected surface and seal it against repeat seepage.", 2),
            ("Final combined inspection", "Electrical", "Confirm dry surfaces, safe wiring and no recurrence.", 3),
        ],
    },
    {
        "key": "ac_not_cooling",
        "match": ["ac", "cooling", "cool", "compressor", "gas", "refrigerant"],
        "title": "Air conditioner cooling failure",
        "tasks": [
            ("Airflow & filter service", "AC Service & Repair", "Clean filters, blower and check airflow before charging gas.", 1),
            ("Pressure test & gas top-up", "AC Service & Repair", "Measure pressures and top up refrigerant only if required.", 2),
            ("Cooling performance verification", "AC Service & Repair", "Verify delta-T and document cooling performance after repair.", 3),
        ],
    },
    {
        "key": "appliance_drainage",
        "match": ["washing", "drain", "pump", "not draining", "spin"],
        "title": "Washing machine drainage failure",
        "tasks": [
            ("Drain line & filter check", "Washing Machine Repair", "Clear lint filter and inspect the drain hose for blockage.", 1),
            ("Drain pump inspection / replacement", "Washing Machine Repair", "Test the drain pump and replace it if electrically failed.", 2),
            ("Wash cycle verification", "Washing Machine Repair", "Run a full cycle and confirm drainage with evidence.", 3),
        ],
    },
    {
        "key": "fridge_not_cooling",
        "match": ["fridge", "refrigerator", "freezer", "cooling"],
        "title": "Refrigerator cooling failure",
        "tasks": [
            ("Electrical & thermostat diagnosis", "Refrigerator Repair", "Test compressor start circuit, relay and thermostat.", 1),
            ("Sealed-system / gas service", "Refrigerator Repair", "Leak test and gas charging if the sealed system is deficient.", 2),
            ("Temperature stabilisation check", "Refrigerator Repair", "Verify compartment temperatures after service.", 3),
        ],
    },
    {
        "key": "deep_clean_and_pest",
        "match": ["cockroach", "pest", "termite", "cleaning", "dirty"],
        "title": "Deep cleaning with pest treatment",
        "tasks": [
            ("Deep cleaning", "Full Home Deep Cleaning", "Clean the affected areas and remove food sources.", 1),
            ("Pest treatment", "General Pest Control", "Apply approved treatment after cleaning is complete.", 2),
            ("Post-treatment inspection", "General Pest Control", "Verify treatment effectiveness and advise on prevention.", 3),
        ],
    },
]

# Default mission template when nothing matches.
DEFAULT_MISSION_TEMPLATE = ("Service visit", "General service visit to diagnose and resolve the reported problem.")
